openapi: "3.0.0"
info:
  version: 1.0.0
  title: jsonSchemaTestNoLogin
paths: 
  /test:
     get:
         responses:
             "200":
                 content:
                     application/json:
                         schema:
                             type: string
                 description: a